### PR TITLE
New features regarding OpenMP and compilers, Also CircleCI fixes

### PR DESCRIPTION
**Pull request by Longbowman**
Hi 

These three commits represents changes that is done to setup.py and Circleci config.yml. 
It checks OS type and if answer is OSx it checks for GCC installed. if GCC is installed it adds compiler and linker args for OpenMP. 
As for CircleCI it adds tests for 3.5, 3.6 and 3.7 python and 1.17 and 1.18 Numpy 

Some suggestions until you merge: 
1) Please do some real testing (as I am not an application developer I can't test it on cirtcleci and I can't run OpenMP tests). Especially please test for Mac that doesn't have GCC
2) I don't see a reason why this check on GCC should work only for OSx  and not Linux 
3) As Numpy 1.18 has still dev0 status I advice to not test it for now 

Thanks 
Archil

### CODE REVIEW

**Comment by Longbowman** [comment]
As you can see some tests passed. Here are the reasons of tests not passed:
1) anaconda supports max 1.16.5 version of numpy. source https://anaconda.org/anaconda/numpy
2) numpy 1.14.2 is not supported on python 3.7
3) mdtraj is not supported in some anaconda version 

What are your suggestions?

**Comment by justinrporter** [comment]
Some things to fix:
- It looks like the "np1.15" tests are still building with numpy 1.14 based on the print statements at the end of the section "Install numpy, cython, mdtraj" of the build. (I wonder if this accounts for the fact that these tests failed? I don't think we're intending to support numpy 1.14...)
- It looks like the logic of `if 'gcc' in  distutils.ccompiler.get_default_compiler(): use_openmp = False` is backwards; use `openmp` should be false if gcc is *not* in the default compiler list.
- It looks like `distutils.ccompiler.get_default_compiler()` returns only `unix` on my system. Perahaps you should use `platform.python_compiler` instead as suggested by [this SO post](https://stackoverflow.com/questions/39421201/how-to-get-the-specific-c-compiler-type-from-python-distutils).

**Comment by justinrporter** [comment]
Could you comment on the different cython versions that are being tested? I see some builds that use 0.26.1 and some that use 0.29.2. Why?

**Comment by Longbowman** [comment]
> Could you comment on the different cython versions that are being tested? I see some builds that use 0.26.1 and some that use 0.29.2. Why?

It is because Cython version 0.29.2 is only supported by Python version 3.7

**Comment by justinrporter** [comment]
Additionally, I notice that the "Restoring Cache" and "Saving Cache" sections of the build are now broken, but are still working in master. This will need to be fixed as well.

**Comment by justinrporter** [comment]
Finally, we discussed making mpi4py optional, which means all tests in the in the "non-MPI tests" block should pass without MPI. This means we should install mpi4py _after_ running those tests.

**Comment by Longbowman** [comment]
> Additionally, I notice that the "Restoring Cache" and "Saving Cache" sections of the build are now broken, but are still working in master. This will need to be fixed as well.
as far as I know this doesn't affect on testing other then speed. 
anyway i will address this issue

**Comment by Longbowman** [comment]
> Finally, we discussed making mpi4py optional, which means all tests in the in the "non-MPI tests" block should pass without MPI. This means we should install mpi4py _after_ running those tests.

so you say that we remove mpi4py from setup.py and add this into circleci? because if you want to install with mpi4py it should be present on setup.py. Can we have separate flag for mpi4py?

**Comment by Longbowman** [comment]
> I don't think this is correct. According to the [setup.py](https://github.com/cython/cython/blob/0.29.x/setup.py#L17) for the 0.29 branch (now on 0.29.13), versions are constrained to be `>=2.6, !=3.0.*, !=3.1.*, !=3.2.*`. Also, [mdtraj requires cython 0.29](https://github.com/mdtraj/mdtraj/blob/master/setup.py#L284), and I can compile that just fine under python 3.6 on my laptop.

I am sorry but you are wrong: you should not search it not in the cython but in anaconda repositories. this is why we dumped numpy version 1.17 and 1.18 because newest version of anaconda numpy was 1.16.5. 

> I'm working on figuring out why the python3.5 tests are failing. It looks like some kind of C-level problem, based on the output ("free(): invalid size" and "corrupted double-linked list"), but I'm having trouble reproducing it, even on the circleci image. (I think it might actually be that the test is just so slow on this machine that it gets nuked by the time out?)

that may need to set larger timeout value?

**Pull request merged**
